/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;
import java.util.List;
//import java.awt.List;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author rosom
 */
public class CalculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public CalculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        firstLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        firstTextField = new javax.swing.JTextField();
        secondTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        subtractButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        fourLabel = new javax.swing.JLabel();
        sqrtButton = new javax.swing.JButton();
        thirdLabel = new javax.swing.JLabel();
        powButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Калькулятор");

        firstLabel.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        firstLabel.setText("Введіть число 1");

        secondLabel.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        secondLabel.setText("Введіть число 2");

        firstTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstTextFieldActionPerformed(evt);
            }
        });

        addButton.setText("Додати");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        subtractButton.setText("Відняти");
        subtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractButtonActionPerformed(evt);
            }
        });

        multiplyButton.setText("Помножити");
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        divideButton.setText("Поділити");
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        fourLabel.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N

        sqrtButton.setText("Корінь квадратний");
        sqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtButtonActionPerformed(evt);
            }
        });

        thirdLabel.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N

        powButton.setText("1 степінь 2");
        powButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("By Roman");

        saveButton.setText("Зберегти результат в текстовий документ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstLabel)
                                .addGap(18, 18, 18)
                                .addComponent(firstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(secondLabel)
                                .addGap(18, 18, 18)
                                .addComponent(secondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sqrtButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subtractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(powButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(multiplyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(fourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thirdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secondLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(subtractButton)
                    .addComponent(multiplyButton)
                    .addComponent(divideButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqrtButton)
                    .addComponent(powButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thirdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(fourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        thirdLabel.getAccessibleContext().setAccessibleName(" ");
        powButton.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       int number1,number2;
        try{
        number1= Integer.parseInt(this.firstTextField.getText());
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "Некоректно введено число 1","Помилка", JOptionPane.ERROR_MESSAGE);
        return;}
        
        try{
            
             
        number2= Integer.parseInt(this.secondTextField.getText());
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "Некоректно введено число 2","Помилка", JOptionPane.ERROR_MESSAGE);
        return;}
        int answer= number1+number2;
        this.thirdLabel.setText(" Відповідь: "+answer);
         this.fourLabel.setText("");
         str.add("  #"+this.firstTextField.getText()+"+"+this.secondTextField.getText()+"="+this.thirdLabel.getText());
    }//GEN-LAST:event_addButtonActionPerformed

    private void subtractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractButtonActionPerformed
        int number1, number2;
        int answer=0;
        try {
            number1 = Integer.parseInt(this.firstTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Некоректно введено число 1", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            
             
            number2 = Integer.parseInt(this.secondTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Некоректно введено число 2", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        answer = number1 - number2;
        this.thirdLabel.setText(" Відповідь: " + answer);
         this.fourLabel.setText("");
str.add("  #"+this.firstTextField.getText()+"-"+this.secondTextField.getText()+"="+this.thirdLabel.getText());
    }//GEN-LAST:event_subtractButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        int number1, number2;
        try {
            number1 = Integer.parseInt(this.firstTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Некоректно введено число 1", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
           
              
            number2 = Integer.parseInt(this.secondTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Некоректно введено число 2", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int answer = number1 * number2;
        this.thirdLabel.setText(" Відповідь: " + answer);
         this.fourLabel.setText("");
 str.add("  #"+this.firstTextField.getText()+"*"+this.secondTextField.getText()+"="+this.thirdLabel.getText());
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        double number1, number2;
        try {
            number1 = Integer.parseInt(this.firstTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Некоректно введено число 1", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Integer.parseInt(this.secondTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Некоректно введено число 2", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            
              
            double answer = number1 / number2;
        this.thirdLabel.setText(" Відповідь: " + String.format("%8.2f", answer));
         this.fourLabel.setText("");}
        catch(ArithmeticException e){
            JOptionPane.showMessageDialog(this, "Неможлтво поділити на 0", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
str.add("  #"+this.firstTextField.getText()+"/"+this.secondTextField.getText()+"="+this.thirdLabel.getText());
    }//GEN-LAST:event_divideButtonActionPerformed

    private void sqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtButtonActionPerformed
        int number1, number2;
        try {
            number1 = Integer.parseInt(this.firstTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Некоректно введено число 1", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Integer.parseInt(this.secondTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Некоректно введено число 2", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            
            double answer1 = Math.sqrt(number1);
            double answer2 = Math.sqrt(number2);
            this.thirdLabel.setText(" 1: " + String.format("%8.2f", answer1));
            this.fourLabel.setText(" 2: " + String.format("%8.2f", answer2));
        } catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(this, "Неможлтво поділити", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
        str.add("  #"+this.firstTextField.getText()+" Корінь "+this.thirdLabel.getText());
              str.add("  #"+this.secondTextField.getText()+" Корінь "+this.fourLabel.getText());
    }//GEN-LAST:event_sqrtButtonActionPerformed

    private void powButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powButtonActionPerformed
        double number1, number2;
        try {
            number1 = Integer.parseInt(this.firstTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Некоректно введено число 1", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Integer.parseInt(this.secondTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Некоректно введено число 2", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            
              
            double answer = Math.pow(number1, number2);
            int answer2=(int) answer;
        this.thirdLabel.setText(" Відповідь: " + answer2);
         this.fourLabel.setText("");}
        catch(ArithmeticException e){
            JOptionPane.showMessageDialog(this, "Неможлтво поділити на 0", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
        str.add("  #"+this.firstTextField.getText()+" В степені "+this.secondTextField.getText()+"="+this.thirdLabel.getText());
    }//GEN-LAST:event_powButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
       
         BufferedWriter bufferedWriter=null;
          try {
             
              bufferedWriter=new BufferedWriter(new FileWriter("C:\\Users\\rosom\\OneDrive\\Рабочий стол\\file.txt"));
              for(String str2 :str){
             bufferedWriter.write(str2);}
            bufferedWriter.close();
             
             JOptionPane.showMessageDialog(this, str, "Помилка", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Помилка запису у файл", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
          
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorForm().setVisible(true);
            }
        });
    }
    private List<String> str = new ArrayList<String>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JTextField firstTextField;
    private javax.swing.JLabel fourLabel;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton powButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JTextField secondTextField;
    private javax.swing.JButton sqrtButton;
    private javax.swing.JButton subtractButton;
    private javax.swing.JLabel thirdLabel;
    // End of variables declaration//GEN-END:variables
}
